### PR TITLE
Customize query and highlight

### PR DESCRIPTION
**Pull request by xcaptain**
1. query can be override by callback function
2. highlight option can be set by callback function

### CODE REVIEW

**Comment by xcaptain** [comment]
This commit makes writing complex query dsl possible, below is an example.

```php
$res = Model::search($name, function ($engine, $query, $options) use ($lat, $lng, $radius, $name) {
    $options['body']['query'] = [
        'bool' => [
            'must' => [
                ['match' => ['name' => $name],]
            ],
            'filter' => [
                'geo_distance' => [
                    'distance' => $radius.'m',
                    'location' => ['lat' => $lat, 'lon' => $lng],
                ]
            ]
        ]
    ];
    $options['body']['highlight'] = [
        'fields' => [
            'name' => ['type' => 'plain'],
        ]
    ];
    $options['body']['sort'][] = [
        '_geo_distance' => [
            'location' => [
                'lat' => $lat,
                'lon' => $lng,
            ],
            'order' => 'asc',
            'unit' => 'km',
        ]
    ];
    return $engine->search($options);
})->paginateRaw($perPage);
```

**Comment by kronthto** [comment]
You can already (since 3.0.6) pass a callback that modifies the params passed to ES in any way, just like in the code you've shown.

Actually if I don't miss something I think your change doesn't do anything, as *body*/*highlight* is never set in `$options`:
* https://github.com/ErickTamayo/laravel-scout-elastic/blob/97deb01452f947b3c515545c2ee65804f1a59853/src/ElasticsearchEngine.php#L99-L102
* https://github.com/ErickTamayo/laravel-scout-elastic/blob/97deb01452f947b3c515545c2ee65804f1a59853/src/ElasticsearchEngine.php#L115-L119

**Comment by xcaptain** [comment]
@kronthto Thanks for the review and explanation.

There is truly an inconsistency between my example code and commit about `highlight`, I'll fix that in the following commit.

I still think it's good to give access to invoker to override the `query` option, `numericFilters` option provides a way to extend the `query` but not override. With the ability to override the `query` option, users can get great benefits from the elasticsearch api.

If this PR got approved, then I suggest abandoning  `numericFilters` option, because its usage is subtle and not so direct.

**Comment by kronthto** [comment]
Sorry, I think you misunderstand something: Calling `$engine->search($options)` in your callback-
function does **not** enter `performSearch` again, as `$engine` is already an instance of `Elasticsearch\Client`, so the changes in this PR are unnecessary / never run through. 
You can try it yourself, put a `die('test');` in one of your conditions, run the example, and see that it's not executed. 
Again, it is already possible to fully customize `query` just like you do in the example code.

---

> If this PR got approved, then I suggest abandoning `numericFilters` option, because its usage is subtle and not so direct.

These simple filters always have to be supported to be compatible with *laravel/scout*.

**Comment by xcaptain** [comment]
Thanks, @kronthto I found where I am wrong, still don't know how to use `$this->filters($builder)` to set `numericFilters`, can you give me a hint.

**Comment by kronthto** [comment]
You can simply set them using `->where($field, $value)` on the `Laravel\Scout\Builder`. 
For example, this what I do in a project: I set simple checks on *is_root*/*subtype* using `where`, what is later passed on as a "numeric filter", and extend that query using the callback function to add an extra wildcard-text-search on *title* (this could also be a more complex thing like location search):
```php
$querybuilder = Asset::search($request->query('search'), function (\Elasticsearch\Client $client, $query, $params) use ($request) {
    if ($request->has('headline')) {
        $params['body']['query']['bool']['must'][] = [
            'query_string' => [
                'fields' => ['title'],
                'query' => '*'.$request->get('headline').'*',
            ],
        ];
    }

    return $client->search($params);
})
    ->where('is_root', true)
    ->orderBy('created_at', 'desc');

if ($subtypes = $request->get('subtype')) {
    $querybuilder->where('subtype', $subtypes);
}

$paginator = $querybuilder->paginate(25);
```

**Pull request closed without merging**
