### PR TITLE
Customize searched fields

### PR DESCRIPTION
**Pull request by xcaptain**
to return custom fields from ES, just add a `getSearchableKeys` in corresponding Model, e.g:
```
public function getSearchableKeys()
{
    return ['id', 'location'];
}
```

### CODE REVIEW

**Review by kronthto — COMMENTED** [review]
I wasn't able to properly test it, but a few things I notice in the code:

There should definitely be Model entities being returned, not arrays (`_source`). Right now this breaks existing apps.

I would not fallback (`elseif first keys`) if the user doesn't explicitly opt-in to this feature. Not everyone has all the data in ES and may rely on the DB results.

You still query the DB, I thought the whole point was not to do that and try to build the entities using the data from ES (Pass the data array to the Entitys constructor).

**Comment by xcaptain** [comment]
@kronthto the _source field contains the origin json stored in ES
> The _source field contains the original JSON document body that was passed at index time. The 
> _source field itself is not indexed (and thus is not searchable), but it is stored so that it can be 
> returned when executing fetch requests, like get or search.
https://www.elastic.co/guide/en/elasticsearch/reference/5.6/mapping-source-field.html

This library integrate eloquent and elasticsearch, so I think use `$model->first()` is a reasonable way to get table fields.

If you approve this change, the build error can be fixed by modify the test cases. 😆

**Comment by kronthto** [comment]
My problem with your change is that it breaks existing applications. Look at this side-by-side comparison of the results of calling `Builder::get()`: 
scout_es_pr_79_get_result_comparison

Left is with the latest released version of this package, right is with your PR pulled in (nothing else in my code changed). If further code relies on `Builder::get()` to return a Collection of Model-Entities you can't just change that to a Collection of Collections, there will be errors.


Edit: Plus, what if in `toSearchableArray` I removed a field from indexing, like in my screenshot `api_type`, because I don't want it searched, but I rely on getting it from the Model later in the code (right know it is there because the DB returns it anyways). With this PR it is not there anymore and my app breaks once again. That's why I feel this feature should be opt-in only.

Edit2: Scout even defines the method must return a Collection of models: https://github.com/laravel/scout/blob/c742ada38f7056dba336dae441d9eaf11000cb76/src/Engines/Engine.php#L53

**Comment by kronthto** [comment]
I have thought of something like this: https://github.com/kronthto/laravel-scout-elastic/commit/56242cc33a109b6033b90595c27dcd91f66980bc

**Comment by xcaptain** [comment]
@kronthto This PR is actually meaningless, because current api is enough.
https://github.com/laravel/scout/blob/681c15a26bbc973528af2e77e0bb61981dc07206/src/Builder.php#L140
https://github.com/laravel/scout/blob/681c15a26bbc973528af2e77e0bb61981dc07206/src/Builder.php#L211

use
```
Model::search('query')->raw();
```
or
```
Model::search('query')->paginateRaw();
```
can get the raw result. Transform of result should be done in application code.

Also, you are right, `map` should return a collection of model rather than a collection of collect.

Thanks man!

**Pull request closed without merging**
